package browser.pig.cn.pigpad.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import browser.pig.cn.pigpad.bean.GoodsBean;
import browser.pig.cn.pigpad.bean.StepABean;

import browser.pig.cn.pigpad.db.GoodsBeanDao;
import browser.pig.cn.pigpad.db.StepABeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsBeanDaoConfig;
    private final DaoConfig stepABeanDaoConfig;

    private final GoodsBeanDao goodsBeanDao;
    private final StepABeanDao stepABeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsBeanDaoConfig = daoConfigMap.get(GoodsBeanDao.class).clone();
        goodsBeanDaoConfig.initIdentityScope(type);

        stepABeanDaoConfig = daoConfigMap.get(StepABeanDao.class).clone();
        stepABeanDaoConfig.initIdentityScope(type);

        goodsBeanDao = new GoodsBeanDao(goodsBeanDaoConfig, this);
        stepABeanDao = new StepABeanDao(stepABeanDaoConfig, this);

        registerDao(GoodsBean.class, goodsBeanDao);
        registerDao(StepABean.class, stepABeanDao);
    }
    
    public void clear() {
        goodsBeanDaoConfig.getIdentityScope().clear();
        stepABeanDaoConfig.getIdentityScope().clear();
    }

    public GoodsBeanDao getGoodsBeanDao() {
        return goodsBeanDao;
    }

    public StepABeanDao getStepABeanDao() {
        return stepABeanDao;
    }

}
